global using System.Text;
global using MyCompany.World.Common;
global using MyCompany.World.Common.Entities;
global using CraftSynth.BuildingBlocks.Common;
global using CraftSynth.BuildingBlocks.IO;
global using CraftSynth.BuildingBlocks.Logging;
global using Microsoft.Extensions.DependencyInjection;
global using Serilog.Context;
global using Serilog.Core.Enrichers;
