// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Sat Dec 02 2023 07:01:10 GMT+0100 (Central European Standard Time)",
    message: null,
    git: {
        user: "F4CIO",
        branch: null,
        fullHash: null
    }
};

export default build;